---
- name: Deploy DockerBanking Application on Linux
  hosts: aws_instances  # Update with your actual host group from inventory.ini
  become: true
  tasks:

    - name: Clone DockerBanking repository
      git:
        repo: "https://github.com/sanish11/DockerBanking.git"
        dest: "/srv/git/DockerBanking"
        force: yes

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: "/srv/git/DockerBanking/src"

    - name: Echo deployment completion message
      debug:
        msg: "Deployment completed successfully."
